import type { UserProfile, Pilot, AuditLogEntry, Opportunity } from "./types"

// Sample User Profiles
export const sampleProfiles: UserProfile[] = [
  {
    id: "user-alice-001",
    name: "Alice Chen",
    email: "alice.chen@example.com",
    role: "entrepreneur",
    availability: "30+ hrs/week",
    skills: [
      "Data Analysis",
      "Python",
      "Machine Learning",
      "Project Management",
      "Technical Writing",
      "API Integration",
    ],
    certifications: [], // No verified license
    experienceYears: 5,
    deviceAccess: ["Laptop", "Smartphone"],
    internetReliable: true,
    willingToUpskill: true,
    willingToPartnerLicensed: true,
    preferredRoles: ["Project Lead", "Technical Contributor"],
    languagePrefs: ["English", "Mandarin"],
    consent: true,
    createdAt: "2024-01-15T10:00:00Z",
    matchResult: {
      score: 82,
      fitLevel: "High",
      rationale: [
        "High availability (30+ hrs/week) matches pilot demands",
        "Strong technical skills in data and ML",
        "Lacks verified license for regulated tasks — partner fallback recommended",
        "Willing to partner with licensed professionals",
      ],
    },
  },
  {
    id: "user-bas-002",
    name: "Bas van der Berg",
    email: "bas.vdb@example.com",
    role: "mentor",
    availability: "10-20 hrs/week",
    skills: [
      "Clinical Research",
      "Medical Devices",
      "Regulatory Compliance",
      "Quality Assurance",
      "Documentation",
      "Training",
    ],
    certifications: [
      {
        id: "cert-001",
        name: "Medical Device Calibration Specialist",
        issuer: "EU Medical Device Authority",
        registryId: "EUMDA-2024-78432",
        issuedAt: "2023-06-01T00:00:00Z",
        expiresAt: "2026-06-01T00:00:00Z",
        verified: true,
      },
    ],
    experienceYears: 12,
    deviceAccess: ["Laptop", "Tablet", "Smartphone"],
    internetReliable: true,
    willingToUpskill: true,
    willingToPartnerLicensed: false,
    preferredRoles: ["Mentor", "Reviewer", "Compliance Advisor"],
    languagePrefs: ["English", "Dutch", "German"],
    consent: true,
    createdAt: "2024-01-10T08:30:00Z",
    matchResult: {
      score: 78,
      fitLevel: "High",
      rationale: [
        "Verified license for medical device calibration",
        "Strong regulatory and compliance expertise",
        "Moderate availability suitable for mentoring roles",
        "Extensive experience (12 years) in clinical research",
      ],
    },
  },
  {
    id: "user-carol-003",
    name: "Carol Martinez",
    email: "carol.m@example.com",
    role: "student",
    availability: "<10 hrs/week",
    skills: ["Basic Excel", "Data Entry", "Customer Service"],
    certifications: [],
    experienceYears: 1,
    deviceAccess: ["Smartphone"],
    internetReliable: false,
    willingToUpskill: true,
    willingToPartnerLicensed: true,
    preferredRoles: ["Learner", "Support Assistant"],
    languagePrefs: ["English", "Spanish"],
    consent: true,
    createdAt: "2024-01-20T14:00:00Z",
    matchResult: {
      score: 35,
      fitLevel: "Low",
      rationale: [
        "Limited availability (<10 hrs/week)",
        "Early-stage learner with basic skills",
        "Unreliable internet may impact remote work",
        "Recommended pathway: Training and micro-task opportunities",
      ],
    },
  },
]



// Sample Pilots
export const samplePilots: Pilot[] = [
  {
    id: "pilot-001",
    title: "Local Marketplace Content",
    description:
      "Create and curate product listings for a community marketplace platform. Tasks include writing descriptions, categorizing items, and basic image editing.",
    ownerId: "user-alice-001",
    ownerName: "Alice Chen",
    jurisdictions: ["United States", "Canada"],
    protectedActivityFlags: [], // Non-protected
    expectedKPIs: "200 listings/month, 95% accuracy rate, <24hr turnaround",
    status: "approved",
    fitBadge: "High",
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-18T09:00:00Z",
    evidence: [],
  },
  {
    id: "pilot-002",
    title: "Clinical Data Collection Pilot",
    description:
      "Assist in collecting and organizing patient feedback data for a clinical trial. Requires handling of sensitive health information under supervision.",
    ownerId: "user-alice-001",
    ownerName: "Alice Chen",
    jurisdictions: ["European Union"],
    protectedActivityFlags: ["Health Data Handling", "Clinical Research"],
    expectedKPIs: "500 records/month, 99% data integrity, GDPR compliance",
    status: "under_review",
    fitBadge: "Medium",
    createdAt: "2024-01-17T14:30:00Z",
    updatedAt: "2024-01-19T16:00:00Z",
    evidence: [
      {
        id: "evidence-001",
        pilotId: "pilot-002",
        filename: "data_handling_cert.pdf",
        issuer: "Health Data Institute",
        registryId: "HDI-2024-PENDING",
        issuedAt: "2024-01-01T00:00:00Z",
        checksum: "sha256:a1b2c3d4e5f6...",
        verified: "pending",
        fileUrl: "/mock/evidence/data_handling_cert.pdf",
        mimeType: "application/pdf",
        uploadedAt: "2024-01-17T14:35:00Z",
      },
    ],
    partnerFallbackNote: "Partner with licensed clinical data manager for oversight of protected activities.",
  },
  {
    id: "pilot-003",
    title: "Medical Device Calibration",
    description:
      "Perform calibration and quality checks on medical diagnostic equipment. Requires certified professional with valid medical device certification.",
    ownerId: "user-bas-002",
    ownerName: "Bas van der Berg",
    jurisdictions: ["European Union", "United Kingdom"],
    protectedActivityFlags: ["Medical Device Operation", "Calibration Certification Required"],
    expectedKPIs: "50 devices/month, 100% compliance rate, documented audit trail",
    status: "approved",
    fitBadge: "High",
    createdAt: "2024-01-12T09:00:00Z",
    updatedAt: "2024-01-14T11:00:00Z",
    evidence: [
      {
        id: "evidence-002",
        pilotId: "pilot-003",
        filename: "medical_device_license.pdf",
        issuer: "EU Medical Device Authority",
        registryId: "EUMDA-2024-78432",
        issuedAt: "2023-06-01T00:00:00Z",
        expiresAt: "2026-06-01T00:00:00Z",
        checksum: "sha256:f7e8d9c0b1a2...",
        verified: "verified",
        fileUrl: "/mock/evidence/medical_device_license.pdf",
        mimeType: "application/pdf",
        uploadedAt: "2024-01-12T09:05:00Z",
      },
    ],
  },
]

// Sample Audit Log
export const sampleAuditLog: AuditLogEntry[] = [
  {
    id: "audit-001",
    timestamp: "2024-01-12T09:05:00Z",
    userId: "user-bas-002",
    userName: "Bas van der Berg",
    action: "upload_evidence",
    resourceType: "evidence",
    resourceId: "evidence-002",
    details: "Uploaded medical_device_license.pdf",
    pilotId: "pilot-003",
  },
  {
    id: "audit-002",
    timestamp: "2024-01-12T09:10:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "verify_license",
    resourceType: "evidence",
    resourceId: "evidence-002",
    details: "License verified: EUMDA-2024-78432 - Status: verified",
    pilotId: "pilot-003",
  },
  {
    id: "audit-003",
    timestamp: "2024-01-14T11:00:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "approve_pilot",
    resourceType: "pilot",
    resourceId: "pilot-003",
    details: "Pilot approved - all evidence verified",
    pilotId: "pilot-003",
  },
  {
    id: "audit-004",
    timestamp: "2024-01-16T11:00:00Z",
    userId: "user-alice-001",
    userName: "Alice Chen",
    action: "create_pilot",
    resourceType: "pilot",
    resourceId: "pilot-001",
    details: "Created pilot: Local Marketplace Content",
    pilotId: "pilot-001",
  },
  {
    id: "audit-005",
    timestamp: "2024-01-17T14:35:00Z",
    userId: "user-alice-001",
    userName: "Alice Chen",
    action: "upload_evidence",
    resourceType: "evidence",
    resourceId: "evidence-001",
    details: "Uploaded data_handling_cert.pdf (pending verification)",
    pilotId: "pilot-002",
  },
  {
    id: "audit-006",
    timestamp: "2024-01-18T09:00:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "approve_pilot",
    resourceType: "pilot",
    resourceId: "pilot-001",
    details: "Pilot approved - non-protected activity",
    pilotId: "pilot-001",
  },
  {
    id: "audit-007",
    timestamp: "2024-01-19T16:00:00Z",
    userId: "mentor-001",
    userName: "Review Committee",
    action: "request_clarification",
    resourceType: "pilot",
    resourceId: "pilot-002",
    details: "Requested additional documentation for clinical data handling",
    pilotId: "pilot-002",
  },
]

// Sample Opportunities
export const sampleOpportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Healthcare Data Analysis Assistant",
    description:
      "Analyze patient outcome data and create reports for clinical research teams. Work under supervision of licensed clinical researcher.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["Data Analysis", "Excel", "Python"],
      certifications: [],
      minExperienceYears: 2,
      jurisdictions: ["European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: ["Health Data Handling"],
    compensation: "$25-35/hour",
    duration: "3 months",
    maxParticipants: 3,
    currentParticipants: 1,
    deadline: "2024-03-01T00:00:00Z",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
    expectedROI: "$8K-12K profit in 3 months",
    initialTimeToCash: "2-3 weeks",
    successEstimate: 75,
    assessmentNotes: "Strong demand for healthcare analytics. Market research shows consistent need.",
    ideationDocument: {
      id: "doc-hda-ideation-001",
      name: "Healthcare Analytics Service - Ideation",
      type: "ideation",
      content: "# Healthcare Data Analysis Service\n\n## Problem Statement\nClinical research teams struggle with data analysis, spending 40% of their time on manual data processing instead of insights generation.\n\n## Solution Overview\nProvide specialized healthcare data analysis services with focus on patient outcome analytics, clinical trial data processing, and research reporting.\n\n## Target Market\n- Small to medium clinical research organizations\n- Individual researchers at universities\n- Healthcare startups conducting studies\n\n## Unique Value Proposition\n- HIPAA/GDPR compliant processes\n- Domain expertise in clinical research\n- Faster turnaround than traditional analytics firms\n- Cost-effective pricing for smaller organizations\n\n## Initial Services\n1. Patient outcome data analysis\n2. Clinical trial statistical analysis\n3. Research report generation\n4. Data visualization for presentations\n\n## Success Metrics\n- 5 initial clients in first 3 months\n- 95% data accuracy rate\n- <48 hour turnaround time\n- 4.5+ client satisfaction rating",
      uploadedBy: "user-bas-002",
      uploadedByName: "Bas van der Berg",
      uploadedAt: "2024-01-08T09:00:00Z",
      lastModified: "2024-01-09T14:30:00Z",
      lastModifiedBy: "user-bas-002",
      lastModifiedByName: "Bas van der Berg",
      version: 2,
    },
    businessCaseDocument: {
      id: "doc-hda-bizcase-001",
      name: "Healthcare Analytics - Business Case",
      type: "business_case",
      content: "# Business Case: Healthcare Data Analysis Service\n\n## Executive Summary\nLaunch a specialized healthcare data analysis service targeting small clinical research teams with $8K-12K projected profit in first 3 months.\n\n## Market Analysis\n**Market Size**: $2.3B healthcare analytics market growing at 12% CAGR\n**Target Segment**: Small research organizations (500+ in EU alone)\n**Competitive Gap**: Most competitors focus on enterprise clients, leaving small teams underserved\n\n## Financial Projections\n**Startup Costs**: $2,500\n- Software licenses: $800\n- Marketing: $1,000\n- Legal/compliance review: $700\n\n**Revenue Model**:\n- Hourly rate: $25-35/hour\n- Monthly retainer: $2,000-4,000\n- Project-based: $1,500-5,000\n\n**Break-even**: 2-3 weeks with 2 active clients\n**ROI**: 320-480% in first quarter\n\n## Risk Assessment\n**High Risk**: GDPR/HIPAA compliance requirements\n**Mitigation**: Partner with certified consultant, use de-identified data initially\n\n**Medium Risk**: Client acquisition timeline\n**Mitigation**: Start with academic connections, offer first project at reduced rate\n\n## Resource Requirements\n- 1 data analyst (10-20 hrs/week)\n- 1 compliance advisor (consulting basis)\n- Software: Python, R, Excel, secure data platform\n\n## Go-to-Market Strategy\n1. Month 1: Build portfolio with 2 pilot clients (academic connections)\n2. Month 2: Launch targeted LinkedIn outreach to research coordinators\n3. Month 3: Attend 2 clinical research networking events\n\n## Success Criteria\n- 5 paying clients by month 3\n- 95% data accuracy\n- Zero compliance violations\n- $8K minimum profit",
      uploadedBy: "user-bas-002",
      uploadedByName: "Bas van der Berg",
      uploadedAt: "2024-01-09T11:00:00Z",
      lastModified: "2024-01-10T08:45:00Z",
      lastModifiedBy: "user-bas-002",
      lastModifiedByName: "Bas van der Berg",
      version: 1,
    },
    risks: [
      {
        id: "risk-hda-1",
        description: "Data privacy compliance requirements (HIPAA/GDPR) may require legal review",
        severity: "high",
        mitigation: "Partner with certified healthcare data compliance consultant. Use only de-identified data sets initially.",
        likelihood: "likely",
      },
      {
        id: "risk-hda-2",
        description: "Client acquisition may be slow in healthcare sector due to procurement cycles",
        severity: "medium",
        mitigation: "Start with smaller clinics and individual practitioners. Build portfolio of case studies.",
        likelihood: "possible",
      },
    ],
  },
  {
    id: "opp-002",
    title: "Medical Device Documentation Specialist",
    description:
      "Create and maintain technical documentation for medical devices. Requires understanding of regulatory compliance.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["Technical Writing", "Documentation", "Regulatory Compliance"],
      certifications: ["Medical Device Calibration Specialist"],
      minExperienceYears: 5,
      jurisdictions: ["European Union", "United Kingdom"],
      availability: "30+ hrs/week",
      deviceAccess: ["Laptop", "Tablet"],
      internetRequired: true,
    },
    protectedActivityFlags: ["Medical Device Operation", "Calibration Certification Required"],
    compensation: "$45-60/hour",
    duration: "6 months",
    maxParticipants: 2,
    currentParticipants: 0,
    deadline: "2024-02-15T00:00:00Z",
    createdAt: "2024-01-08T14:00:00Z",
    updatedAt: "2024-01-12T10:00:00Z",
    expectedROI: "$15K-20K in 6 months",
    initialTimeToCash: "4-6 weeks",
    successEstimate: 85,
    assessmentNotes: "High demand for regulatory documentation specialists. Strong certification requirement ensures quality.",
    ideationDocument: {
      id: "doc-mdd-ideation-001",
      name: "Medical Device Documentation - Ideation",
      type: "ideation",
      content: "# Medical Device Documentation Service\n\n## Opportunity\nMedical device manufacturers need specialized technical writers who understand regulatory requirements. Current market has 6-month wait times.\n\n## Service Offering\nProvide regulatory-compliant technical documentation for medical devices including:\n- User manuals\n- Service documentation\n- Regulatory submission packages\n- Quality system documentation\n\n## Competitive Advantage\n- EU Medical Device Calibration Specialist certification\n- 12 years clinical research experience\n- Faster turnaround than agencies\n- Personal service vs large firm bureaucracy\n\n## Target Clients\n- Medical device startups (pre-market approval)\n- Small manufacturers expanding to EU market\n- Contract manufacturers needing documentation support\n\n## Pricing Strategy\n- Hourly: $45-60/hour (below agency rates of $75-100)\n- Project-based: $3K-8K per device documentation package\n- Retainer: $4K-6K/month for ongoing support",
      uploadedBy: "user-bas-002",
      uploadedByName: "Bas van der Berg",
      uploadedAt: "2024-01-08T14:00:00Z",
      lastModified: "2024-01-08T14:00:00Z",
      lastModifiedBy: "user-bas-002",
      lastModifiedByName: "Bas van der Berg",
      version: 1,
    },
    businessCaseDocument: {
      id: "doc-mdd-bizcase-001",
      name: "Medical Device Documentation - Business Case",
      type: "business_case",
      content: "# Business Case: Medical Device Documentation Specialist\n\n## Market Opportunity\n**Problem**: Medical device companies face 6-month backlogs for regulatory documentation\n**Solution**: Certified specialist offering faster, personalized service\n**Market Size**: 2,700+ medical device companies in EU requiring documentation\n\n## Financial Analysis\n**Investment Required**: $1,200\n- Professional liability insurance: $800/year\n- Marketing materials: $200\n- Software/templates: $200\n\n**Revenue Projections**:\n- Month 1-2: 1 client project ($5,000)\n- Month 3-4: 2 concurrent projects ($8,000)\n- Month 5-6: 1 retainer + 1 project ($10,000)\n- **Total 6-month revenue**: $23,000\n- **Net profit**: $15,800 (after $1,200 investment + $6,000 time costs)\n\n**ROI**: 1,317% over 6 months\n\n## Competitive Positioning\n**Advantages**:\n- Verified certification (trust signal)\n- 30% lower cost than agencies\n- 50% faster turnaround\n- Direct communication (no account managers)\n\n**Risks**:\n- Regulatory changes requiring re-certification\n- Liability exposure (mitigated with insurance)\n- Client payment delays (require 50% upfront)\n\n## Go-to-Market\n1. LinkedIn outreach to MedTech founders\n2. Partner with medical device industry associations\n3. Offer free regulatory compliance checklist as lead magnet\n4. Attend 2 MedTech conferences (budget: $1,500)\n\n## Success Metrics\n- 3 clients by month 2\n- 100% regulatory compliance on all submissions\n- 4.8+ client rating\n- $15K+ profit by month 6",
      uploadedBy: "user-bas-002",
      uploadedByName: "Bas van der Berg",
      uploadedAt: "2024-01-08T15:30:00Z",
      lastModified: "2024-01-12T09:15:00Z",
      lastModifiedBy: "user-bas-002",
      lastModifiedByName: "Bas van der Berg",
      version: 2,
    },
    risks: [
      {
        id: "risk-mdd-1",
        description: "Regulatory changes could require significant re-training and documentation updates",
        severity: "medium",
        mitigation: "Subscribe to regulatory update services. Build ongoing learning into project budgets.",
        likelihood: "possible",
      },
      {
        id: "risk-mdd-2",
        description: "Certification maintenance costs and time commitment",
        severity: "low",
        mitigation: "Factor certification renewal into annual planning. Leverage employer sponsorship when possible.",
        likelihood: "unlikely",
      },
    ],
  },
  {
    id: "opp-003",
    title: "Entry-Level Data Entry Support",
    description:
      "Basic data entry and organization tasks. Great opportunity for learners to build experience in a supportive environment.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "draft",
    requirements: {
      skills: ["Data Entry", "Excel"],
      certifications: [],
      minExperienceYears: 0,
      jurisdictions: ["United States", "Canada", "European Union"],
      availability: "<10 hrs/week",
      deviceAccess: ["Smartphone"],
      internetRequired: false,
    },
    protectedActivityFlags: [],
    compensation: "$12-15/hour",
    duration: "Ongoing",
    maxParticipants: 10,
    currentParticipants: 0,
    createdAt: "2024-01-20T11:00:00Z",
    updatedAt: "2024-01-20T11:00:00Z",
    expectedROI: "$500-1K supplemental income",
    initialTimeToCash: "1-2 weeks",
    successEstimate: 60,
    assessmentNotes: "Low barrier to entry, ideal for skill-building. Limited income potential but reliable.",
    risks: [
      {
        id: "risk-ded-1",
        description: "Automation and AI tools may reduce demand for basic data entry work",
        severity: "high",
        mitigation: "Focus on data validation and quality control. Upskill to data analysis roles progressively.",
        likelihood: "likely",
      },
    ],
  },
  {
    id: "opp-004",
    title: "AI Automation Agency",
    description:
      "Design and deploy automated workflows for small businesses using no-code tools and LLMs. Projects are scoped as short sprints.",
    mentorId: "user-alice-001",
    mentorName: "Alice Chen",
    status: "published",
    requirements: {
      skills: ["No-Code Automation", "Prompt Engineering", "API Integration"],
      certifications: [],
      minExperienceYears: 1,
      jurisdictions: ["United States", "European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$30-50/hour",
    duration: "1 month",
    maxParticipants: 3,
    currentParticipants: 0,
    deadline: "2024-04-01T00:00:00Z",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-01T09:00:00Z",
    expectedROI: "150-200% on client projects",
    initialTimeToCash: "3-5 weeks",
    successEstimate: 70,
    assessmentNotes: "Growing market for AI automation. Requires technical sales skills and reliable delivery.",
    risks: [
      {
        id: "risk-aia-1",
        description: "Rapid AI technology changes may render solutions obsolete quickly",
        severity: "high",
        mitigation: "Focus on platform-agnostic workflows. Build modular solutions that can be updated incrementally.",
        likelihood: "likely",
      },
      {
        id: "risk-aia-2",
        description: "Client expectations may exceed current AI capabilities",
        severity: "medium",
        mitigation: "Set clear scope boundaries. Provide pilot/proof-of-concept before full implementation.",
        likelihood: "possible",
      },
      {
        id: "risk-aia-3",
        description: "Emerging AI regulations could impact service delivery",
        severity: "medium",
        mitigation: "Stay informed on AI governance standards. Include compliance review in project workflows.",
        likelihood: "possible",
      },
    ],
  },
  {
    id: "opp-005",
    title: "SEO-Focused Copywriting (Contract)",
    description:
      "Write persona-driven SEO copy and content briefs for niche B2B audiences. Deliverables include keyword-optimized articles and performance briefs.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["SEO", "Copywriting", "Content Strategy"],
      certifications: [],
      minExperienceYears: 2,
      jurisdictions: ["United States", "Canada", "European Union"],
      availability: "<10 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$20-35/hour",
    duration: "3 months",
    maxParticipants: 5,
    currentParticipants: 0,
    deadline: "2024-05-01T00:00:00Z",
    createdAt: "2024-02-05T10:00:00Z",
    updatedAt: "2024-02-05T10:00:00Z",
    expectedROI: "$3K-6K in 3 months",
    initialTimeToCash: "2-3 weeks",
    successEstimate: 80,
    assessmentNotes: "Proven demand for SEO content. Portfolio and samples accelerate client acquisition.",
    risks: [
      {
        id: "risk-seo-1",
        description: "Search algorithm changes could devalue existing optimization strategies",
        severity: "medium",
        mitigation: "Focus on evergreen content principles. Diversify across multiple platforms and formats.",
        likelihood: "possible",
      },
      {
        id: "risk-seo-2",
        description: "Market saturation with low-cost competitors and AI writing tools",
        severity: "high",
        mitigation: "Specialize in niche B2B sectors. Emphasize strategic content planning over volume writing.",
        likelihood: "likely",
      },
    ],
  },
  {
    id: "opp-006",
    title: "Digital Knowledge Merchant — Template Creator",
    description:
      "Create and publish Notion/Obsidian templates, guides, and micro-products for niche professional audiences. Includes product packaging and basic marketing.",
    mentorId: "user-alice-001",
    mentorName: "Alice Chen",
    status: "published",
    requirements: {
      skills: ["Product Design", "Notion", "Marketing"],
      certifications: [],
      minExperienceYears: 0,
      jurisdictions: ["United States"],
      availability: "<10 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "Revenue share / Project-based",
    duration: "Ongoing",
    maxParticipants: 4,
    currentParticipants: 0,
    createdAt: "2024-02-08T12:00:00Z",
    updatedAt: "2024-02-08T12:00:00Z",
    expectedROI: "$2K-5K passive income",
    initialTimeToCash: "4-8 weeks",
    successEstimate: 65,
    assessmentNotes: "Templates require upfront effort but scale well. Market saturation varies by niche.",
    risks: [
      {
        id: "risk-dkm-1",
        description: "Template marketplaces becoming oversaturated with similar products",
        severity: "medium",
        mitigation: "Focus on hyper-specific professional niches. Bundle templates with implementation guides.",
        likelihood: "possible",
      },
    ],
  },
  {
    id: "opp-007",
    title: "Vertical Short-Form Video Agency",
    description:
      "Repurpose long-form content into short video clips for social platforms, including captions, hooks, and thumbnail design.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["Video Editing", "Social Media", "Copywriting"],
      certifications: [],
      minExperienceYears: 1,
      jurisdictions: ["United States", "European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop", "Smartphone"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$25-40/hour",
    duration: "1 month",
    maxParticipants: 6,
    currentParticipants: 1,
    deadline: "2024-04-15T00:00:00Z",
    createdAt: "2024-02-12T08:00:00Z",
    updatedAt: "2024-02-12T08:00:00Z",
    expectedROI: "$4K-8K per month",
    initialTimeToCash: "2-4 weeks",
    successEstimate: 75,
    assessmentNotes: "High demand for video content. Recurring client revenue possible with good quality.",
    risks: [
      {
        id: "risk-vid-1",
        description: "Platform algorithm changes could reduce content reach and client ROI",
        severity: "medium",
        mitigation: "Track performance metrics across platforms. Build multi-platform distribution strategy.",
        likelihood: "possible",
      },
      {
        id: "risk-vid-2",
        description: "Time-intensive production may limit scalability",
        severity: "medium",
        mitigation: "Develop template-based workflows. Consider hiring freelancers for editing overflow.",
        likelihood: "likely",
      },
    ],
  },
  {
    id: "opp-008",
    title: "AI Explainability & Audit Specialist (Contract)",
    description:
      "Support teams by producing human-readable model explanations, audit artifacts, and mitigation recommendations for biased outputs.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["ML Ops", "Model Auditing", "Data Ethics"],
      certifications: [],
      minExperienceYears: 3,
      jurisdictions: ["United States", "European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$50-80/hour",
    duration: "2 months",
    maxParticipants: 2,
    currentParticipants: 0,
    createdAt: "2024-02-15T09:30:00Z",
    updatedAt: "2024-02-15T09:30:00Z",
    expectedROI: "$10K-16K in 2 months",
    initialTimeToCash: "3-5 weeks",
    successEstimate: 70,
    assessmentNotes: "Emerging field with regulatory tailwinds. Requires staying current with AI governance standards.",
    risks: [
      {
        id: "risk-aia-1",
        description: "AI regulations and standards are still evolving rapidly",
        severity: "high",
        mitigation: "Stay current with EU AI Act and other frameworks. Build flexible audit methodologies.",
        likelihood: "likely",
      },
      {
        id: "risk-aia-2",
        description: "Liability concerns for providing audit opinions",
        severity: "medium",
        mitigation: "Work under professional insurance. Frame deliverables as recommendations not certifications.",
        likelihood: "possible",
      },
    ],
  },
  {
    id: "opp-009",
    title: "Managed Microsoft 365 Migration (Quickstart)",
    description:
      "Small-scope migration packages for SMBs moving email and files to Microsoft 365, including governance templates and basic training.",
    mentorId: "user-alice-001",
    mentorName: "Alice Chen",
    status: "published",
    requirements: {
      skills: ["Microsoft 365", "IT Admin", "User Training"],
      certifications: [],
      minExperienceYears: 2,
      jurisdictions: ["United States", "European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$60-100/project",
    duration: "2 weeks",
    maxParticipants: 1,
    currentParticipants: 0,
    createdAt: "2024-02-18T11:00:00Z",
    updatedAt: "2024-02-18T11:00:00Z",
    expectedROI: "$60-100 per project",
    initialTimeToCash: "1-2 weeks",
    successEstimate: 85,
    assessmentNotes: "Repeatable service with steady SMB demand. Low complexity, high volume potential.",
    risks: [
      {
        id: "risk-m365-1",
        description: "Microsoft licensing and pricing changes affecting project economics",
        severity: "low",
        mitigation: "Build buffer into quotes. Stay updated on partner program changes.",
        likelihood: "unlikely",
      },
    ],
  },
  {
    id: "opp-010",
    title: "AWS Landing Zone & Account Setup for SMBs",
    description:
      "Rapid onboarding package to create a secure multi-account AWS structure with baseline security and cost controls.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "published",
    requirements: {
      skills: ["AWS", "Cloud Security", "Infrastructure as Code"],
      certifications: [],
      minExperienceYears: 2,
      jurisdictions: ["United States", "European Union"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$80-150/project",
    duration: "1 month",
    maxParticipants: 1,
    currentParticipants: 0,
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-02-20T10:00:00Z",    expectedROI: "$80-150 per project",
    initialTimeToCash: "2-3 weeks",
    successEstimate: 75,
    assessmentNotes: "Growing cloud adoption creates consistent demand. Template-based approach enables scale.",  },
  {
    id: "opp-011",
    title: "Local SEO Fixer — Small Business Pack",
    description:
      "On-page local SEO audits and quick fixes for local businesses to improve search visibility and map listings.",
    mentorId: "user-alice-001",
    mentorName: "Alice Chen",
    status: "published",
    requirements: {
      skills: ["Local SEO", "Google My Business", "Copywriting"],
      certifications: [],
      minExperienceYears: 1,
      jurisdictions: ["United States", "Netherlands"],
      availability: "<10 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "$150-500/project",
    duration: "2 weeks",
    maxParticipants: 4,
    currentParticipants: 0,
    createdAt: "2024-02-22T09:00:00Z",
    updatedAt: "2024-02-22T09:00:00Z",
    expectedROI: "$1.5K-5K per month",
    initialTimeToCash: "1-2 weeks",
    successEstimate: 80,
    assessmentNotes: "High demand from local businesses. Scalable with standardized audit process.",
    risks: [
      {
        id: "risk-seof-1",
        description: "Google Business Profile guideline changes affecting optimization tactics",
        severity: "medium",
        mitigation: "Focus on fundamentals (NAP consistency, reviews). Monitor policy updates regularly.",
        likelihood: "possible",
      },
    ],
  },
  {
    id: "opp-012",
    title: "Tiny-SaaS Billing Dashboard (MVP)",
    description:
      "Build a minimal billing dashboard for solopreneurs to manage subscriptions, invoices and simple analytics as an MVP product.",
    mentorId: "user-bas-002",
    mentorName: "Bas van der Berg",
    status: "draft",
    requirements: {
      skills: ["React", "Stripe", "Backend"],
      certifications: [],
      minExperienceYears: 1,
      jurisdictions: ["United States"],
      availability: "10-20 hrs/week",
      deviceAccess: ["Laptop"],
      internetRequired: true,
    },
    protectedActivityFlags: [],
    compensation: "Revenue share / Project-based",
    duration: "1 month",
    maxParticipants: 3,
    currentParticipants: 0,
    createdAt: "2024-02-25T08:30:00Z",
    updatedAt: "2024-02-25T08:30:00Z",
    expectedROI: "Potential MRR $500-2K if validated",
    initialTimeToCash: "6-8 weeks",
    successEstimate: 55,
    assessmentNotes: "Product-market fit unproven. Higher risk but significant upside if validated.",
    risks: [
      {
        id: "risk-saas-1",
        description: "Product-market fit unproven, may not gain traction",
        severity: "high",
        mitigation: "Start with MVP validation interviews. Pivot quickly based on user feedback.",
        likelihood: "likely",
      },
      {
        id: "risk-saas-2",
        description: "Payment processing integration complexity and compliance",
        severity: "medium",
        mitigation: "Use Stripe or similar with PCI compliance built-in. Start with simple subscription model.",
        likelihood: "possible",
      },
    ],
  },
]

// Protected activity flags options
export const protectedActivityOptions = [
  "Health Data Handling",
  "Clinical Research",
  "Medical Device Operation",
  "Calibration Certification Required",
  "Financial Data Processing",
  "Legal Document Handling",
  "Child Safety Related",
  "Pharmaceutical Handling",
]

// Skills options for the form
export const skillsOptions = [
  "Data Analysis",
  "Python",
  "Machine Learning",
  "Project Management",
  "Technical Writing",
  "API Integration",
  "Clinical Research",
  "Medical Devices",
  "Regulatory Compliance",
  "Quality Assurance",
  "Documentation",
  "Training",
  "Customer Service",
  "Data Entry",
  "Excel",
  "JavaScript",
  "Database Management",
  "UI/UX Design",
]

// Jurisdiction options
export const jurisdictionOptions = [
  "United States",
  "Canada",
  "European Union",
  "United Kingdom",
  "Australia",
  "Singapore",
  "Japan",
]

// Compensation options for opportunity creation
export const compensationOptions = [
  "$10-15/hour",
  "$15-25/hour",
  "$25-35/hour",
  "$35-45/hour",
  "$45-60/hour",
  "$60+/hour",
  "Project-based",
  "Stipend",
]

// Duration options for opportunity creation
export const durationOptions = ["1 week", "2 weeks", "1 month", "3 months", "6 months", "12 months", "Ongoing"]
