import type { UserProfile, Pilot, AuditLogEntry } from "./types"

// Sample User Profiles
export const sampleProfiles: UserProfile[] = [
  {
    id: "user-alice-001",
    name: "Alice Chen",
    email: "alice.chen@example.com",
    role: "entrepreneur",
    availability: "30+ hrs/week",
    skills: [
      "Data Analysis",
      "Python",
      "Machine Learning",
      "Project Management",
      "Technical Writing",
      "API Integration",
    ],
    certifications: [], // No verified license
    experienceYears: 5,
    deviceAccess: ["Laptop", "Smartphone"],
    internetReliable: true,
    willingToUpskill: true,
    willingToPartnerLicensed: true,
    preferredRoles: ["Project Lead", "Technical Contributor"],
    languagePrefs: ["English", "Mandarin"],
    consent: true,
    createdAt: "2024-01-15T10:00:00Z",
    matchResult: {
      score: 82,
      fitLevel: "High",
      rationale: [
        "High availability (30+ hrs/week) matches pilot demands",
        "Strong technical skills in data and ML",
        "Lacks verified license for regulated tasks — partner fallback recommended",
        "Willing to partner with licensed professionals",
      ],
    },
  },
  {
    id: "user-bas-002",
    name: "Bas van der Berg",
    email: "bas.vdb@example.com",
    role: "mentor",
    availability: "10-20 hrs/week",
    skills: [
      "Clinical Research",
      "Medical Devices",
      "Regulatory Compliance",
      "Quality Assurance",
      "Documentation",
      "Training",
    ],
    certifications: [
      {
        id: "cert-001",
        name: "Medical Device Calibration Specialist",
        issuer: "EU Medical Device Authority",
        registryId: "EUMDA-2024-78432",
        issuedAt: "2023-06-01T00:00:00Z",
        expiresAt: "2026-06-01T00:00:00Z",
        verified: true,
      },
    ],
    experienceYears: 12,
    deviceAccess: ["Laptop", "Tablet", "Smartphone"],
    internetReliable: true,
    willingToUpskill: true,
    willingToPartnerLicensed: false,
    preferredRoles: ["Mentor", "Reviewer", "Compliance Advisor"],
    languagePrefs: ["English", "Dutch", "German"],
    consent: true,
    createdAt: "2024-01-10T08:30:00Z",
    matchResult: {
      score: 78,
      fitLevel: "High",
      rationale: [
        "Verified license for medical device calibration",
        "Strong regulatory and compliance expertise",
        "Moderate availability suitable for mentoring roles",
        "Extensive experience (12 years) in clinical research",
      ],
    },
  },
  {
    id: "user-carol-003",
    name: "Carol Martinez",
    email: "carol.m@example.com",
    role: "student",
    availability: "<10 hrs/week",
    skills: ["Basic Excel", "Data Entry", "Customer Service"],
    certifications: [],
    experienceYears: 1,
    deviceAccess: ["Smartphone"],
    internetReliable: false,
    willingToUpskill: true,
    willingToPartnerLicensed: true,
    preferredRoles: ["Learner", "Support Assistant"],
    languagePrefs: ["English", "Spanish"],
    consent: true,
    createdAt: "2024-01-20T14:00:00Z",
    matchResult: {
      score: 35,
      fitLevel: "Low",
      rationale: [
        "Limited availability (<10 hrs/week)",
        "Early-stage learner with basic skills",
        "Unreliable internet may impact remote work",
        "Recommended pathway: Training and micro-task opportunities",
      ],
    },
  },
]

// Sample Pilots
export const samplePilots: Pilot[] = [
  {
    id: "pilot-001",
    title: "Local Marketplace Content",
    description:
      "Create and curate product listings for a community marketplace platform. Tasks include writing descriptions, categorizing items, and basic image editing.",
    ownerId: "user-alice-001",
    ownerName: "Alice Chen",
    jurisdictions: ["United States", "Canada"],
    protectedActivityFlags: [], // Non-protected
    expectedKPIs: "200 listings/month, 95% accuracy rate, <24hr turnaround",
    status: "approved",
    fitBadge: "High",
    createdAt: "2024-01-16T11:00:00Z",
    updatedAt: "2024-01-18T09:00:00Z",
    evidence: [],
  },
  {
    id: "pilot-002",
    title: "Clinical Data Collection Pilot",
    description:
      "Assist in collecting and organizing patient feedback data for a clinical trial. Requires handling of sensitive health information under supervision.",
    ownerId: "user-alice-001",
    ownerName: "Alice Chen",
    jurisdictions: ["European Union"],
    protectedActivityFlags: ["Health Data Handling", "Clinical Research"],
    expectedKPIs: "500 records/month, 99% data integrity, GDPR compliance",
    status: "under_review",
    fitBadge: "Medium",
    createdAt: "2024-01-17T14:30:00Z",
    updatedAt: "2024-01-19T16:00:00Z",
    evidence: [
      {
        id: "evidence-001",
        pilotId: "pilot-002",
        filename: "data_handling_cert.pdf",
        issuer: "Health Data Institute",
        registryId: "HDI-2024-PENDING",
        issuedAt: "2024-01-01T00:00:00Z",
        checksum: "sha256:a1b2c3d4e5f6...",
        verified: "pending",
        fileUrl: "/mock/evidence/data_handling_cert.pdf",
        mimeType: "application/pdf",
        uploadedAt: "2024-01-17T14:35:00Z",
      },
    ],
    partnerFallbackNote: "Partner with licensed clinical data manager for oversight of protected activities.",
  },
  {
    id: "pilot-003",
    title: "Medical Device Calibration",
    description:
      "Perform calibration and quality checks on medical diagnostic equipment. Requires certified professional with valid medical device certification.",
    ownerId: "user-bas-002",
    ownerName: "Bas van der Berg",
    jurisdictions: ["European Union", "United Kingdom"],
    protectedActivityFlags: ["Medical Device Operation", "Calibration Certification Required"],
    expectedKPIs: "50 devices/month, 100% compliance rate, documented audit trail",
    status: "approved",
    fitBadge: "High",
    createdAt: "2024-01-12T09:00:00Z",
    updatedAt: "2024-01-14T11:00:00Z",
    evidence: [
      {
        id: "evidence-002",
        pilotId: "pilot-003",
        filename: "medical_device_license.pdf",
        issuer: "EU Medical Device Authority",
        registryId: "EUMDA-2024-78432",
        issuedAt: "2023-06-01T00:00:00Z",
        expiresAt: "2026-06-01T00:00:00Z",
        checksum: "sha256:f7e8d9c0b1a2...",
        verified: "verified",
        fileUrl: "/mock/evidence/medical_device_license.pdf",
        mimeType: "application/pdf",
        uploadedAt: "2024-01-12T09:05:00Z",
      },
    ],
  },
]

// Sample Audit Log
export const sampleAuditLog: AuditLogEntry[] = [
  {
    id: "audit-001",
    timestamp: "2024-01-12T09:05:00Z",
    userId: "user-bas-002",
    userName: "Bas van der Berg",
    action: "upload_evidence",
    resourceType: "evidence",
    resourceId: "evidence-002",
    details: "Uploaded medical_device_license.pdf",
    pilotId: "pilot-003",
  },
  {
    id: "audit-002",
    timestamp: "2024-01-12T09:10:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "verify_license",
    resourceType: "evidence",
    resourceId: "evidence-002",
    details: "License verified: EUMDA-2024-78432 - Status: verified",
    pilotId: "pilot-003",
  },
  {
    id: "audit-003",
    timestamp: "2024-01-14T11:00:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "approve_pilot",
    resourceType: "pilot",
    resourceId: "pilot-003",
    details: "Pilot approved - all evidence verified",
    pilotId: "pilot-003",
  },
  {
    id: "audit-004",
    timestamp: "2024-01-16T11:00:00Z",
    userId: "user-alice-001",
    userName: "Alice Chen",
    action: "create_pilot",
    resourceType: "pilot",
    resourceId: "pilot-001",
    details: "Created pilot: Local Marketplace Content",
    pilotId: "pilot-001",
  },
  {
    id: "audit-005",
    timestamp: "2024-01-17T14:35:00Z",
    userId: "user-alice-001",
    userName: "Alice Chen",
    action: "upload_evidence",
    resourceType: "evidence",
    resourceId: "evidence-001",
    details: "Uploaded data_handling_cert.pdf (pending verification)",
    pilotId: "pilot-002",
  },
  {
    id: "audit-006",
    timestamp: "2024-01-18T09:00:00Z",
    userId: "admin-001",
    userName: "System Admin",
    action: "approve_pilot",
    resourceType: "pilot",
    resourceId: "pilot-001",
    details: "Pilot approved - non-protected activity",
    pilotId: "pilot-001",
  },
  {
    id: "audit-007",
    timestamp: "2024-01-19T16:00:00Z",
    userId: "mentor-001",
    userName: "Review Committee",
    action: "request_clarification",
    resourceType: "pilot",
    resourceId: "pilot-002",
    details: "Requested additional documentation for clinical data handling",
    pilotId: "pilot-002",
  },
]

// Protected activity flags options
export const protectedActivityOptions = [
  "Health Data Handling",
  "Clinical Research",
  "Medical Device Operation",
  "Calibration Certification Required",
  "Financial Data Processing",
  "Legal Document Handling",
  "Child Safety Related",
  "Pharmaceutical Handling",
]

// Skills options for the form
export const skillsOptions = [
  "Data Analysis",
  "Python",
  "Machine Learning",
  "Project Management",
  "Technical Writing",
  "API Integration",
  "Clinical Research",
  "Medical Devices",
  "Regulatory Compliance",
  "Quality Assurance",
  "Documentation",
  "Training",
  "Customer Service",
  "Data Entry",
  "Excel",
  "JavaScript",
  "Database Management",
  "UI/UX Design",
]

// Jurisdiction options
export const jurisdictionOptions = [
  "United States",
  "Canada",
  "European Union",
  "United Kingdom",
  "Australia",
  "Singapore",
  "Japan",
]
